import type { Metadata } from "next";

import Navbar from "@/components/navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "BankSathi",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
